/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyViewsIndexRouteImport } from './routes/my-views/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as MyViewsTypescriptCodeWritingRouteImport } from './routes/my-views/typescript-code-writing'
import { Route as MyViewsTableDesignRouteImport } from './routes/my-views/table-design'
import { Route as MyViewsProximityPrincipleRouteImport } from './routes/my-views/proximity-principle'
import { Route as MyViewsNullVsUndefinedRouteImport } from './routes/my-views/null-vs-undefined'
import { Route as MyViewsHandlingTimestampsRouteImport } from './routes/my-views/handling-timestamps'
import { Route as MyViewsDialogDesignRouteImport } from './routes/my-views/dialog-design'
import { Route as MyViewsDataLoadingRouteImport } from './routes/my-views/data-loading'
import { Route as MyViewsButtonDesignRouteImport } from './routes/my-views/button-design'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyViewsIndexRoute = MyViewsIndexRouteImport.update({
  id: '/my-views/',
  path: '/my-views/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyViewsTypescriptCodeWritingRoute =
  MyViewsTypescriptCodeWritingRouteImport.update({
    id: '/my-views/typescript-code-writing',
    path: '/my-views/typescript-code-writing',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyViewsTableDesignRoute = MyViewsTableDesignRouteImport.update({
  id: '/my-views/table-design',
  path: '/my-views/table-design',
  getParentRoute: () => rootRouteImport,
} as any)
const MyViewsProximityPrincipleRoute =
  MyViewsProximityPrincipleRouteImport.update({
    id: '/my-views/proximity-principle',
    path: '/my-views/proximity-principle',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyViewsNullVsUndefinedRoute = MyViewsNullVsUndefinedRouteImport.update({
  id: '/my-views/null-vs-undefined',
  path: '/my-views/null-vs-undefined',
  getParentRoute: () => rootRouteImport,
} as any)
const MyViewsHandlingTimestampsRoute =
  MyViewsHandlingTimestampsRouteImport.update({
    id: '/my-views/handling-timestamps',
    path: '/my-views/handling-timestamps',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyViewsDialogDesignRoute = MyViewsDialogDesignRouteImport.update({
  id: '/my-views/dialog-design',
  path: '/my-views/dialog-design',
  getParentRoute: () => rootRouteImport,
} as any)
const MyViewsDataLoadingRoute = MyViewsDataLoadingRouteImport.update({
  id: '/my-views/data-loading',
  path: '/my-views/data-loading',
  getParentRoute: () => rootRouteImport,
} as any)
const MyViewsButtonDesignRoute = MyViewsButtonDesignRouteImport.update({
  id: '/my-views/button-design',
  path: '/my-views/button-design',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/my-views/button-design': typeof MyViewsButtonDesignRoute
  '/my-views/data-loading': typeof MyViewsDataLoadingRoute
  '/my-views/dialog-design': typeof MyViewsDialogDesignRoute
  '/my-views/handling-timestamps': typeof MyViewsHandlingTimestampsRoute
  '/my-views/null-vs-undefined': typeof MyViewsNullVsUndefinedRoute
  '/my-views/proximity-principle': typeof MyViewsProximityPrincipleRoute
  '/my-views/table-design': typeof MyViewsTableDesignRoute
  '/my-views/typescript-code-writing': typeof MyViewsTypescriptCodeWritingRoute
  '/blog': typeof BlogIndexRoute
  '/my-views': typeof MyViewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/my-views/button-design': typeof MyViewsButtonDesignRoute
  '/my-views/data-loading': typeof MyViewsDataLoadingRoute
  '/my-views/dialog-design': typeof MyViewsDialogDesignRoute
  '/my-views/handling-timestamps': typeof MyViewsHandlingTimestampsRoute
  '/my-views/null-vs-undefined': typeof MyViewsNullVsUndefinedRoute
  '/my-views/proximity-principle': typeof MyViewsProximityPrincipleRoute
  '/my-views/table-design': typeof MyViewsTableDesignRoute
  '/my-views/typescript-code-writing': typeof MyViewsTypescriptCodeWritingRoute
  '/blog': typeof BlogIndexRoute
  '/my-views': typeof MyViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/my-views/button-design': typeof MyViewsButtonDesignRoute
  '/my-views/data-loading': typeof MyViewsDataLoadingRoute
  '/my-views/dialog-design': typeof MyViewsDialogDesignRoute
  '/my-views/handling-timestamps': typeof MyViewsHandlingTimestampsRoute
  '/my-views/null-vs-undefined': typeof MyViewsNullVsUndefinedRoute
  '/my-views/proximity-principle': typeof MyViewsProximityPrincipleRoute
  '/my-views/table-design': typeof MyViewsTableDesignRoute
  '/my-views/typescript-code-writing': typeof MyViewsTypescriptCodeWritingRoute
  '/blog/': typeof BlogIndexRoute
  '/my-views/': typeof MyViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/my-views/button-design'
    | '/my-views/data-loading'
    | '/my-views/dialog-design'
    | '/my-views/handling-timestamps'
    | '/my-views/null-vs-undefined'
    | '/my-views/proximity-principle'
    | '/my-views/table-design'
    | '/my-views/typescript-code-writing'
    | '/blog'
    | '/my-views'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/my-views/button-design'
    | '/my-views/data-loading'
    | '/my-views/dialog-design'
    | '/my-views/handling-timestamps'
    | '/my-views/null-vs-undefined'
    | '/my-views/proximity-principle'
    | '/my-views/table-design'
    | '/my-views/typescript-code-writing'
    | '/blog'
    | '/my-views'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/my-views/button-design'
    | '/my-views/data-loading'
    | '/my-views/dialog-design'
    | '/my-views/handling-timestamps'
    | '/my-views/null-vs-undefined'
    | '/my-views/proximity-principle'
    | '/my-views/table-design'
    | '/my-views/typescript-code-writing'
    | '/blog/'
    | '/my-views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MyViewsButtonDesignRoute: typeof MyViewsButtonDesignRoute
  MyViewsDataLoadingRoute: typeof MyViewsDataLoadingRoute
  MyViewsDialogDesignRoute: typeof MyViewsDialogDesignRoute
  MyViewsHandlingTimestampsRoute: typeof MyViewsHandlingTimestampsRoute
  MyViewsNullVsUndefinedRoute: typeof MyViewsNullVsUndefinedRoute
  MyViewsProximityPrincipleRoute: typeof MyViewsProximityPrincipleRoute
  MyViewsTableDesignRoute: typeof MyViewsTableDesignRoute
  MyViewsTypescriptCodeWritingRoute: typeof MyViewsTypescriptCodeWritingRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MyViewsIndexRoute: typeof MyViewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/': {
      id: '/my-views/'
      path: '/my-views'
      fullPath: '/my-views'
      preLoaderRoute: typeof MyViewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/typescript-code-writing': {
      id: '/my-views/typescript-code-writing'
      path: '/my-views/typescript-code-writing'
      fullPath: '/my-views/typescript-code-writing'
      preLoaderRoute: typeof MyViewsTypescriptCodeWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/table-design': {
      id: '/my-views/table-design'
      path: '/my-views/table-design'
      fullPath: '/my-views/table-design'
      preLoaderRoute: typeof MyViewsTableDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/proximity-principle': {
      id: '/my-views/proximity-principle'
      path: '/my-views/proximity-principle'
      fullPath: '/my-views/proximity-principle'
      preLoaderRoute: typeof MyViewsProximityPrincipleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/null-vs-undefined': {
      id: '/my-views/null-vs-undefined'
      path: '/my-views/null-vs-undefined'
      fullPath: '/my-views/null-vs-undefined'
      preLoaderRoute: typeof MyViewsNullVsUndefinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/handling-timestamps': {
      id: '/my-views/handling-timestamps'
      path: '/my-views/handling-timestamps'
      fullPath: '/my-views/handling-timestamps'
      preLoaderRoute: typeof MyViewsHandlingTimestampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/dialog-design': {
      id: '/my-views/dialog-design'
      path: '/my-views/dialog-design'
      fullPath: '/my-views/dialog-design'
      preLoaderRoute: typeof MyViewsDialogDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/data-loading': {
      id: '/my-views/data-loading'
      path: '/my-views/data-loading'
      fullPath: '/my-views/data-loading'
      preLoaderRoute: typeof MyViewsDataLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-views/button-design': {
      id: '/my-views/button-design'
      path: '/my-views/button-design'
      fullPath: '/my-views/button-design'
      preLoaderRoute: typeof MyViewsButtonDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  MyViewsButtonDesignRoute: MyViewsButtonDesignRoute,
  MyViewsDataLoadingRoute: MyViewsDataLoadingRoute,
  MyViewsDialogDesignRoute: MyViewsDialogDesignRoute,
  MyViewsHandlingTimestampsRoute: MyViewsHandlingTimestampsRoute,
  MyViewsNullVsUndefinedRoute: MyViewsNullVsUndefinedRoute,
  MyViewsProximityPrincipleRoute: MyViewsProximityPrincipleRoute,
  MyViewsTableDesignRoute: MyViewsTableDesignRoute,
  MyViewsTypescriptCodeWritingRoute: MyViewsTypescriptCodeWritingRoute,
  BlogIndexRoute: BlogIndexRoute,
  MyViewsIndexRoute: MyViewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
