/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuleOfThumbIndexRouteImport } from './routes/rule-of-thumb/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as RuleOfThumbTypescriptCodeWritingRouteImport } from './routes/rule-of-thumb/typescript-code-writing'
import { Route as RuleOfThumbTableDesignRouteImport } from './routes/rule-of-thumb/table-design'
import { Route as RuleOfThumbProximityPrincipleRouteImport } from './routes/rule-of-thumb/proximity-principle'
import { Route as RuleOfThumbNullVsUndefinedRouteImport } from './routes/rule-of-thumb/null-vs-undefined'
import { Route as RuleOfThumbHandlingTimestampsRouteImport } from './routes/rule-of-thumb/handling-timestamps'
import { Route as RuleOfThumbDialogDesignRouteImport } from './routes/rule-of-thumb/dialog-design'
import { Route as RuleOfThumbDataLoadingRouteImport } from './routes/rule-of-thumb/data-loading'
import { Route as RuleOfThumbButtonDesignRouteImport } from './routes/rule-of-thumb/button-design'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleOfThumbIndexRoute = RuleOfThumbIndexRouteImport.update({
  id: '/rule-of-thumb/',
  path: '/rule-of-thumb/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleOfThumbTypescriptCodeWritingRoute =
  RuleOfThumbTypescriptCodeWritingRouteImport.update({
    id: '/rule-of-thumb/typescript-code-writing',
    path: '/rule-of-thumb/typescript-code-writing',
    getParentRoute: () => rootRouteImport,
  } as any)
const RuleOfThumbTableDesignRoute = RuleOfThumbTableDesignRouteImport.update({
  id: '/rule-of-thumb/table-design',
  path: '/rule-of-thumb/table-design',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleOfThumbProximityPrincipleRoute =
  RuleOfThumbProximityPrincipleRouteImport.update({
    id: '/rule-of-thumb/proximity-principle',
    path: '/rule-of-thumb/proximity-principle',
    getParentRoute: () => rootRouteImport,
  } as any)
const RuleOfThumbNullVsUndefinedRoute =
  RuleOfThumbNullVsUndefinedRouteImport.update({
    id: '/rule-of-thumb/null-vs-undefined',
    path: '/rule-of-thumb/null-vs-undefined',
    getParentRoute: () => rootRouteImport,
  } as any)
const RuleOfThumbHandlingTimestampsRoute =
  RuleOfThumbHandlingTimestampsRouteImport.update({
    id: '/rule-of-thumb/handling-timestamps',
    path: '/rule-of-thumb/handling-timestamps',
    getParentRoute: () => rootRouteImport,
  } as any)
const RuleOfThumbDialogDesignRoute = RuleOfThumbDialogDesignRouteImport.update({
  id: '/rule-of-thumb/dialog-design',
  path: '/rule-of-thumb/dialog-design',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleOfThumbDataLoadingRoute = RuleOfThumbDataLoadingRouteImport.update({
  id: '/rule-of-thumb/data-loading',
  path: '/rule-of-thumb/data-loading',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleOfThumbButtonDesignRoute = RuleOfThumbButtonDesignRouteImport.update({
  id: '/rule-of-thumb/button-design',
  path: '/rule-of-thumb/button-design',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rule-of-thumb/button-design': typeof RuleOfThumbButtonDesignRoute
  '/rule-of-thumb/data-loading': typeof RuleOfThumbDataLoadingRoute
  '/rule-of-thumb/dialog-design': typeof RuleOfThumbDialogDesignRoute
  '/rule-of-thumb/handling-timestamps': typeof RuleOfThumbHandlingTimestampsRoute
  '/rule-of-thumb/null-vs-undefined': typeof RuleOfThumbNullVsUndefinedRoute
  '/rule-of-thumb/proximity-principle': typeof RuleOfThumbProximityPrincipleRoute
  '/rule-of-thumb/table-design': typeof RuleOfThumbTableDesignRoute
  '/rule-of-thumb/typescript-code-writing': typeof RuleOfThumbTypescriptCodeWritingRoute
  '/blog': typeof BlogIndexRoute
  '/rule-of-thumb': typeof RuleOfThumbIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rule-of-thumb/button-design': typeof RuleOfThumbButtonDesignRoute
  '/rule-of-thumb/data-loading': typeof RuleOfThumbDataLoadingRoute
  '/rule-of-thumb/dialog-design': typeof RuleOfThumbDialogDesignRoute
  '/rule-of-thumb/handling-timestamps': typeof RuleOfThumbHandlingTimestampsRoute
  '/rule-of-thumb/null-vs-undefined': typeof RuleOfThumbNullVsUndefinedRoute
  '/rule-of-thumb/proximity-principle': typeof RuleOfThumbProximityPrincipleRoute
  '/rule-of-thumb/table-design': typeof RuleOfThumbTableDesignRoute
  '/rule-of-thumb/typescript-code-writing': typeof RuleOfThumbTypescriptCodeWritingRoute
  '/blog': typeof BlogIndexRoute
  '/rule-of-thumb': typeof RuleOfThumbIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rule-of-thumb/button-design': typeof RuleOfThumbButtonDesignRoute
  '/rule-of-thumb/data-loading': typeof RuleOfThumbDataLoadingRoute
  '/rule-of-thumb/dialog-design': typeof RuleOfThumbDialogDesignRoute
  '/rule-of-thumb/handling-timestamps': typeof RuleOfThumbHandlingTimestampsRoute
  '/rule-of-thumb/null-vs-undefined': typeof RuleOfThumbNullVsUndefinedRoute
  '/rule-of-thumb/proximity-principle': typeof RuleOfThumbProximityPrincipleRoute
  '/rule-of-thumb/table-design': typeof RuleOfThumbTableDesignRoute
  '/rule-of-thumb/typescript-code-writing': typeof RuleOfThumbTypescriptCodeWritingRoute
  '/blog/': typeof BlogIndexRoute
  '/rule-of-thumb/': typeof RuleOfThumbIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/rule-of-thumb/button-design'
    | '/rule-of-thumb/data-loading'
    | '/rule-of-thumb/dialog-design'
    | '/rule-of-thumb/handling-timestamps'
    | '/rule-of-thumb/null-vs-undefined'
    | '/rule-of-thumb/proximity-principle'
    | '/rule-of-thumb/table-design'
    | '/rule-of-thumb/typescript-code-writing'
    | '/blog'
    | '/rule-of-thumb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/rule-of-thumb/button-design'
    | '/rule-of-thumb/data-loading'
    | '/rule-of-thumb/dialog-design'
    | '/rule-of-thumb/handling-timestamps'
    | '/rule-of-thumb/null-vs-undefined'
    | '/rule-of-thumb/proximity-principle'
    | '/rule-of-thumb/table-design'
    | '/rule-of-thumb/typescript-code-writing'
    | '/blog'
    | '/rule-of-thumb'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/rule-of-thumb/button-design'
    | '/rule-of-thumb/data-loading'
    | '/rule-of-thumb/dialog-design'
    | '/rule-of-thumb/handling-timestamps'
    | '/rule-of-thumb/null-vs-undefined'
    | '/rule-of-thumb/proximity-principle'
    | '/rule-of-thumb/table-design'
    | '/rule-of-thumb/typescript-code-writing'
    | '/blog/'
    | '/rule-of-thumb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RuleOfThumbButtonDesignRoute: typeof RuleOfThumbButtonDesignRoute
  RuleOfThumbDataLoadingRoute: typeof RuleOfThumbDataLoadingRoute
  RuleOfThumbDialogDesignRoute: typeof RuleOfThumbDialogDesignRoute
  RuleOfThumbHandlingTimestampsRoute: typeof RuleOfThumbHandlingTimestampsRoute
  RuleOfThumbNullVsUndefinedRoute: typeof RuleOfThumbNullVsUndefinedRoute
  RuleOfThumbProximityPrincipleRoute: typeof RuleOfThumbProximityPrincipleRoute
  RuleOfThumbTableDesignRoute: typeof RuleOfThumbTableDesignRoute
  RuleOfThumbTypescriptCodeWritingRoute: typeof RuleOfThumbTypescriptCodeWritingRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RuleOfThumbIndexRoute: typeof RuleOfThumbIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/': {
      id: '/rule-of-thumb/'
      path: '/rule-of-thumb'
      fullPath: '/rule-of-thumb'
      preLoaderRoute: typeof RuleOfThumbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/typescript-code-writing': {
      id: '/rule-of-thumb/typescript-code-writing'
      path: '/rule-of-thumb/typescript-code-writing'
      fullPath: '/rule-of-thumb/typescript-code-writing'
      preLoaderRoute: typeof RuleOfThumbTypescriptCodeWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/table-design': {
      id: '/rule-of-thumb/table-design'
      path: '/rule-of-thumb/table-design'
      fullPath: '/rule-of-thumb/table-design'
      preLoaderRoute: typeof RuleOfThumbTableDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/proximity-principle': {
      id: '/rule-of-thumb/proximity-principle'
      path: '/rule-of-thumb/proximity-principle'
      fullPath: '/rule-of-thumb/proximity-principle'
      preLoaderRoute: typeof RuleOfThumbProximityPrincipleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/null-vs-undefined': {
      id: '/rule-of-thumb/null-vs-undefined'
      path: '/rule-of-thumb/null-vs-undefined'
      fullPath: '/rule-of-thumb/null-vs-undefined'
      preLoaderRoute: typeof RuleOfThumbNullVsUndefinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/handling-timestamps': {
      id: '/rule-of-thumb/handling-timestamps'
      path: '/rule-of-thumb/handling-timestamps'
      fullPath: '/rule-of-thumb/handling-timestamps'
      preLoaderRoute: typeof RuleOfThumbHandlingTimestampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/dialog-design': {
      id: '/rule-of-thumb/dialog-design'
      path: '/rule-of-thumb/dialog-design'
      fullPath: '/rule-of-thumb/dialog-design'
      preLoaderRoute: typeof RuleOfThumbDialogDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/data-loading': {
      id: '/rule-of-thumb/data-loading'
      path: '/rule-of-thumb/data-loading'
      fullPath: '/rule-of-thumb/data-loading'
      preLoaderRoute: typeof RuleOfThumbDataLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-of-thumb/button-design': {
      id: '/rule-of-thumb/button-design'
      path: '/rule-of-thumb/button-design'
      fullPath: '/rule-of-thumb/button-design'
      preLoaderRoute: typeof RuleOfThumbButtonDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  RuleOfThumbButtonDesignRoute: RuleOfThumbButtonDesignRoute,
  RuleOfThumbDataLoadingRoute: RuleOfThumbDataLoadingRoute,
  RuleOfThumbDialogDesignRoute: RuleOfThumbDialogDesignRoute,
  RuleOfThumbHandlingTimestampsRoute: RuleOfThumbHandlingTimestampsRoute,
  RuleOfThumbNullVsUndefinedRoute: RuleOfThumbNullVsUndefinedRoute,
  RuleOfThumbProximityPrincipleRoute: RuleOfThumbProximityPrincipleRoute,
  RuleOfThumbTableDesignRoute: RuleOfThumbTableDesignRoute,
  RuleOfThumbTypescriptCodeWritingRoute: RuleOfThumbTypescriptCodeWritingRoute,
  BlogIndexRoute: BlogIndexRoute,
  RuleOfThumbIndexRoute: RuleOfThumbIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
